Default: &defaults
  database: backend.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: backend_test.sqlite3
  <<: *defaults

Staging:
  database: backend_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: backend_production.sqlite3
  poolsize: 100
  <<: *defaults
